export let keyData = [
	[
		{'code': 'Escape', 'width': 10, 'shiftTitles': ['Escape', '', '', '', '' ]},
		{'code': 'F1', 'width': 10, 'shiftTitles': ['F1', '', '', '', '' ]},
		{'code': 'F2', 'width': 10, 'shiftTitles': ['F2', '', '', '', '' ]},
		{'code': 'F3', 'width': 10, 'shiftTitles': ['F3', '', '', '', '' ]},
		{'code': 'F4', 'width': 10, 'shiftTitles': ['F4', '', '', '', '' ]},
		{'code': 'F5', 'width': 10, 'shiftTitles': ['F5', '', '', '', '' ]},
		{'code': 'F6', 'width': 10, 'shiftTitles': ['F6', '', '', '', '' ]},
		{'code': 'F7', 'width': 10, 'shiftTitles': ['F7', '', '', '', '' ]},
		{'code': 'F8', 'width': 10, 'shiftTitles': ['F8', '', '', '', '' ]},
		{'code': 'F9', 'width': 10, 'shiftTitles': ['F9', '', '', '', '' ]},
		{'code': 'F10', 'width': 10, 'shiftTitles': ['F10', '', '', '', '' ]},
		{'code': 'F11', 'width': 10, 'shiftTitles': ['F11', '', '', '', '' ]},
		{'code': 'F12', 'width': 10, 'shiftTitles': ['F12', '', '', '', '' ]},
	],
	[
		{'code': 'Backquote', 'width': 10, 'shiftTitles': ['Backquote', '`', '', '', '' ]},
		{'code': 'Digit1', 'width': 10, 'shiftTitles': ['Digit1', '1', '', '1', '' ]},
		{'code': 'Digit2', 'width': 10, 'shiftTitles': ['Digit2', '2', '', '2', '' ]},
		{'code': 'Digit3', 'width': 10, 'shiftTitles': ['Digit3', '3', '', '3', '' ]},
		{'code': 'Digit4', 'width': 10, 'shiftTitles': ['Digit4', '4', '', '4', '' ]},
		{'code': 'Digit5', 'width': 10, 'shiftTitles': ['Digit5', '5', '', '5', '' ]},
		{'code': 'Digit6', 'width': 10, 'shiftTitles': ['Digit6', '6', '', '6', '' ]},
		{'code': 'Digit7', 'width': 10, 'shiftTitles': ['Digit7', '7', '', '7', '' ]},
		{'code': 'Digit8', 'width': 10, 'shiftTitles': ['Digit8', '8', '', '8', '' ]},
		{'code': 'Digit9', 'width': 10, 'shiftTitles': ['Digit9', '9', '', '9', '' ]},
		{'code': 'Digit0', 'width': 10, 'shiftTitles': ['Digit0', '0', '', '0', '' ]},
		{'code': 'Minus', 'width': 10, 'shiftTitles': ['Minus', '-', '', '', '' ]},
		{'code': 'Equal', 'width': 10, 'shiftTitles': ['Equal', '=', '', '', '' ]},
		{'code': 'Backspace', 'width': 10, 'shiftTitles': ['Backspace', '', '', '', '' ]},
	],
	[
		{'code': 'Tab', 'width': 10, 'shiftTitles': ['Tab', '', '', '', '' ]},
		{'code': 'KeyQ', 'width': 10, 'shiftTitles': ['KeyQ', 'q', 'Q', '', '' ]},
		{'code': 'KeyW', 'width': 10, 'shiftTitles': ['KeyW', 'w', '', '', '' ]},
		{'code': 'KeyE', 'width': 10, 'shiftTitles': ['KeyE', 'e', '', '', '' ]},
		{'code': 'KeyR', 'width': 10, 'shiftTitles': ['KeyR', 'r', '', '', '' ]},
		{'code': 'KeyT', 'width': 10, 'shiftTitles': ['KeyT', 't', '', '', '' ]},
		{'code': 'KeyY', 'width': 10, 'shiftTitles': ['KeyY', 'y', '', '', '' ]},
		{'code': 'KeyU', 'width': 10, 'shiftTitles': ['KeyU', 'u', '', '', '' ]},
		{'code': 'KeyI', 'width': 10, 'shiftTitles': ['KeyI', 'i', '', '', '' ]},
		{'code': 'KeyO', 'width': 10, 'shiftTitles': ['KeyO', 'o', '', '', '' ]},
		{'code': 'KeyP', 'width': 10, 'shiftTitles': ['KeyP', 'p', '', '', '' ]},
		{'code': 'BracketLeft', 'width': 10, 'shiftTitles': ['BracketLeft', '', '', '', '' ]},
		{'code': 'BracketRight', 'width': 10, 'shiftTitles': ['BracketRight', '', '', '', '' ]},
		{'code': 'Backslash', 'width': 10, 'shiftTitles': ['Backslash', '', '', '', '' ]},
	],
	[
		{'code': 'CapsLock', 'width': 10, 'shiftTitles': ['CapsLock', '', '', '', '' ]},
		{'code': 'KeyA', 'width': 10, 'shiftTitles': ['KeyA', '', '', '', '' ]},
		{'code': 'KeyS', 'width': 10, 'shiftTitles': ['KeyS', '', '', '', '' ]},
		{'code': 'KeyD', 'width': 10, 'shiftTitles': ['KeyD', '', '', '', '' ]},
		{'code': 'KeyF', 'width': 10, 'shiftTitles': ['KeyF', '', '', '', '' ]},
		{'code': 'KeyG', 'width': 10, 'shiftTitles': ['KeyG', '', '', '', '' ]},
		{'code': 'KeyH', 'width': 10, 'shiftTitles': ['KeyH', '', '', '', '' ]},
		{'code': 'KeyJ', 'width': 10, 'shiftTitles': ['KeyJ', '', '', '', '' ]},
		{'code': 'KeyK', 'width': 10, 'shiftTitles': ['KeyK', '', '', '', '' ]},
		{'code': 'KeyL', 'width': 10, 'shiftTitles': ['KeyL', '', '', '', '' ]},
		{'code': 'Semicolon', 'width': 10, 'shiftTitles': ['Semicolon', '', '', '', '' ]},
		{'code': 'Quote', 'width': 10, 'shiftTitles': ['Quote', '', '', '', '' ]},
		{'code': 'Enter', 'width': 10, 'shiftTitles': ['Enter', '', '', '', '' ]},
	],
	[
		{'code': 'ShiftLeft', 'width': 10, 'shiftTitles': ['ShiftLeft', '', '', '', '' ]},
		{'code': 'KeyZ', 'width': 10, 'shiftTitles': ['KeyZ', '', '', '', '' ]},
		{'code': 'KeyX', 'width': 10, 'shiftTitles': ['KeyX', '', '', '', '' ]},
		{'code': 'KeyC', 'width': 10, 'shiftTitles': ['KeyC', '', '', '', '' ]},
		{'code': 'KeyV', 'width': 10, 'shiftTitles': ['KeyV', '', '', '', '' ]},
		{'code': 'KeyB', 'width': 10, 'shiftTitles': ['KeyB', '', '', '', '' ]},
		{'code': 'KeyN', 'width': 10, 'shiftTitles': ['KeyN', '', '', '', '' ]},
		{'code': 'KeyM', 'width': 10, 'shiftTitles': ['KeyM', '', '', '', '' ]},
		{'code': 'Comma', 'width': 10, 'shiftTitles': ['Comma', '', '', '', '' ]},
		{'code': 'Period', 'width': 10, 'shiftTitles': ['Period', '', '', '', '' ]},
		{'code': 'Slash', 'width': 10, 'shiftTitles': ['Slash', '', '', '', '' ]},
		{'code': 'ShiftRight', 'width': 10, 'shiftTitles': ['ShiftRight', '', '', '', '' ]},
	],
	[
		{'code': 'ControlLeft', 'width': 10, 'shiftTitles': ['ControlLeft', '', '', '', '' ]},
		{'code': 'MetaLeft', 'width': 10, 'shiftTitles': ['MetaLeft', '', '', '', '' ]},
		{'code': 'Space', 'width': 10, 'shiftTitles': ['Space', '', '', '', '' ]},
		{'code': 'MetaRight', 'width': 10, 'shiftTitles': ['MetaRight', '', '', '', '' ]},
		{'code': 'ControlRight', 'width': 10, 'shiftTitles': ['ControlRight', '', '', '', '' ]},
		{'code': 'AltRight', 'width': 10, 'shiftTitles': ['AltRight', '', '', '', '' ]},
		{'code': 'ControlRight', 'width': 10, 'shiftTitles': ['ControlRight', '', '', '', '' ]},
		{'code': 'ArrowLeft', 'width': 10, 'shiftTitles': ['ArrowLeft', '', '', '', '' ]},
		{'code': 'ArrowDown', 'width': 10, 'shiftTitles': ['ArrowDown', '', '', '', '' ]},
		{'code': 'ArrowUp', 'width': 10, 'shiftTitles': ['ArrowUp', '', '', '', '' ]},
		{'code': 'ArrowRight', 'width': 10, 'shiftTitles': ['ArrowRight', '', '', '', '' ]},
	]

]