export let keyData = [
	[
		{'code': 'Escape', 'width': 15, 'shiftTitles': ['', '', '', '&#x1F600', 'esc' ]},
		{'code': 'F1', 'width': 10, 'shiftTitles': ['&#x1F600;', '&#x1F600;', '&#x1F600;', '&#x1F600;', 'F1' ]},
		{'code': 'F2', 'width': 10, 'shiftTitles': ['&#x1F601;', '&#x1F601;', '&#x1F601;', '&#x1F601;', 'F2' ]},
		{'code': 'F3', 'width': 10, 'shiftTitles': ['&#x1F602;', '&#x1F602;', '&#x1F602;', '&#x1F602;', 'F3' ]},
		{'code': 'F4', 'width': 10, 'shiftTitles': ['&#x1F603;', '&#x1F603;', '&#x1F603;', '&#x1F603;', 'F4' ]},
		{'code': 'F5', 'width': 10, 'shiftTitles': ['&#x1F604;', '&#x1F604;', '&#x1F604;', '&#x1F604;', 'F5' ]},
		{'code': 'F6', 'width': 10, 'shiftTitles': ['&#x1F605;', '&#x1F605;', '&#x1F605;', '&#x1F605;', 'F6' ]},
		{'code': 'F7', 'width': 10, 'shiftTitles': ['&#x1F606;', '&#x1F606;', '&#x1F606;', '&#x1F606;', 'F7' ]},
		{'code': 'F8', 'width': 10, 'shiftTitles': ['&#x1F607;', '&#x1F607;', '&#x1F607;', '&#x1F607;', 'F8' ]},
		{'code': 'F9', 'width': 10, 'shiftTitles': ['&#x1F608;', '&#x1F608;', '&#x1F608;', '&#x1F608;', 'F9' ]},
		{'code': 'F10', 'width': 10, 'shiftTitles': ['&#x1F609;', '&#x1F609;', '&#x1F609;', '&#x1F609;', 'F10' ]},
		{'code': 'F11', 'width': 10, 'shiftTitles': ['&#x1F60A;', '&#x1F60A;', '&#x1F60A;', '&#x1F60A;', 'F11' ]},
		{'code': 'F12', 'width': 10, 'shiftTitles': ['&#x1F60B;', '&#x1F60B;', '&#x1F60B;', '&#x1F60B;', 'F12' ]},
		{'code': 'F13', 'width': 10, 'shiftTitles': ['&#x1F608;', '&#x1F608;', '&#x1F608;', '&#x1F608;', 'F13' ]},
	],
	[
		{'code': 'Backquote', 'width': 10, 'shiftTitles': ['`', '~', 'ё', 'Ё', '' ]},
		{'code': 'Digit1', 'width': 10, 'shiftTitles': ['1', '!', '1', '!', '' ]},
		{'code': 'Digit2', 'width': 10, 'shiftTitles': ['2', '@', '2', '"', '' ]},
		{'code': 'Digit3', 'width': 10, 'shiftTitles': ['3', '#', '3', '№', '' ]},
		{'code': 'Digit4', 'width': 10, 'shiftTitles': ['4', '$', '4', ';', '' ]},
		{'code': 'Digit5', 'width': 10, 'shiftTitles': ['5', '%', '5', '%', '' ]},
		{'code': 'Digit6', 'width': 10, 'shiftTitles': ['6', '^', '6', ':', '' ]},
		{'code': 'Digit7', 'width': 10, 'shiftTitles': ['7', '&', '7', '?', '' ]},
		{'code': 'Digit8', 'width': 10, 'shiftTitles': ['8', '*', '8', '*', '' ]},
		{'code': 'Digit9', 'width': 10, 'shiftTitles': ['9', '(', '9', '(', '' ]},
		{'code': 'Digit0', 'width': 10, 'shiftTitles': ['0', ')', '0', ')', '' ]},
		{'code': 'Minus', 'width': 10, 'shiftTitles': ['-', '_', '-', '_', '' ]},
		{'code': 'Equal', 'width': 10, 'shiftTitles': ['=', '+', '=', '+', '' ]},
		{'code': 'Backspace', 'width': 15, 'shiftTitles': ['', '', '', '', 'backspace' ]},
	],
	[
		{'code': 'Tab', 'width': 15, 'shiftTitles': ['\t', '\t', '\t', '\t', 'tab' ]},
		{'code': 'KeyQ', 'width': 10, 'shiftTitles': [ 'q', 'Q', 'й', 'Й' , '']},
		{'code': 'KeyW', 'width': 10, 'shiftTitles': ['w', 'W', 'ц', 'Ц', '' ]},
		{'code': 'KeyE', 'width': 10, 'shiftTitles': ['e', 'E', 'у', 'У', '' ]},
		{'code': 'KeyR', 'width': 10, 'shiftTitles': ['r', 'R', 'к', 'К', '' ]},
		{'code': 'KeyT', 'width': 10, 'shiftTitles': ['t', 'T', 'е', 'Е', '' ]},
		{'code': 'KeyY', 'width': 10, 'shiftTitles': ['y', 'Y', 'н', 'Н', '' ]},
		{'code': 'KeyU', 'width': 10, 'shiftTitles': ['u', 'U', 'г', 'Г', '' ]},
		{'code': 'KeyI', 'width': 10, 'shiftTitles': ['i', 'I', 'ш', 'Ш', '' ]},
		{'code': 'KeyO', 'width': 10, 'shiftTitles': ['o', 'O', 'щ', 'Щ', '' ]},
		{'code': 'KeyP', 'width': 10, 'shiftTitles': ['p', 'P', 'з', 'З', '' ]},
		{'code': 'BracketLeft', 'width': 10, 'shiftTitles': ['[', '{', 'х', 'Х', '' ]},
		{'code': 'BracketRight', 'width': 10, 'shiftTitles': [']', '}', 'ъ', 'Ъ', '' ]},
		{'code': 'Backslash', 'width': 10, 'shiftTitles': ['\\', '|', '', '', '' ]},
	],
	[
		{'code': 'CapsLock', 'width': 17, 'shiftTitles': ['', '', '', '', 'caps' ]},
		{'code': 'KeyA', 'width': 10, 'shiftTitles': ['a', 'A', 'ф', 'Ф', '' ]},
		{'code': 'KeyS', 'width': 10, 'shiftTitles': ['s', 'S', 'ы', 'Ы', '' ]},
		{'code': 'KeyD', 'width': 10, 'shiftTitles': ['d', 'D', 'в', 'В', '' ]},
		{'code': 'KeyF', 'width': 10, 'shiftTitles': ['f', 'F', 'а', 'А', '' ]},
		{'code': 'KeyG', 'width': 10, 'shiftTitles': ['g', 'G', 'п', 'П', '' ]},
		{'code': 'KeyH', 'width': 10, 'shiftTitles': ['h', 'H', 'р', 'Р', '' ]},
		{'code': 'KeyJ', 'width': 10, 'shiftTitles': ['j', 'J', 'о', 'О', '' ]},
		{'code': 'KeyK', 'width': 10, 'shiftTitles': ['k', 'K', 'л', 'Л', '' ]},
		{'code': 'KeyL', 'width': 10, 'shiftTitles': ['l', 'L', 'д', 'Д', '' ]},
		{'code': 'Semicolon', 'width': 10, 'shiftTitles': [';', ':', 'ж', 'Ж', '' ]},
		{'code': 'Quote', 'width': 10, 'shiftTitles': ['\'', '"', 'э', 'Э', '' ]},
		{'code': 'Enter', 'width': 17, 'shiftTitles': ['\n', '\n', '\n', '\n', 'enter' ]},
	],
	[
		{'code': 'ShiftLeft', 'width': 20, 'shiftTitles': ['', '', '', '', 'shift' ]},
		{'code': 'KeyZ', 'width': 10, 'shiftTitles': ['z', 'Z', 'я', 'Я', '' ]},
		{'code': 'KeyX', 'width': 10, 'shiftTitles': ['x', 'X', 'ч', 'Ч', '' ]},
		{'code': 'KeyC', 'width': 10, 'shiftTitles': ['c', 'C', 'с', 'С', '' ]},
		{'code': 'KeyV', 'width': 10, 'shiftTitles': ['v', 'V', 'м', 'М', '' ]},
		{'code': 'KeyB', 'width': 10, 'shiftTitles': ['b', 'B', 'и', 'И', '' ]},
		{'code': 'KeyN', 'width': 10, 'shiftTitles': ['n', 'N', 'т', 'Т', '' ]},
		{'code': 'KeyM', 'width': 10, 'shiftTitles': ['m', 'M', 'ь', 'Ь', '' ]},
		{'code': 'Comma', 'width': 10, 'shiftTitles': [',', '<', 'б', 'Б', '' ]},
		{'code': 'Period', 'width': 10, 'shiftTitles': ['.', '>', 'ю', 'Ю', '' ]},
		{'code': 'Slash', 'width': 12, 'shiftTitles': ['/', '?', '.', '.', '' ]},
		{'code': 'ArrowUp', 'width': 10, 'shiftTitles': ['⯅', '⯅', '⯅', '⯅', '⯅' ]},
		{'code': 'ShiftRight', 'width': 10, 'shiftTitles': ['', '', '', '', 'shift' ]},
	],
	[
		{'code': 'ControlLeft', 'width': 10, 'shiftTitles': ['en', 'EN', 'ru', 'RU', '']},
		{'code': 'MetaLeft2', 'width': 10, 'shiftTitles': ['', '', '', '', '' ]},
		{'code': 'MetaLeft', 'width': 10, 'shiftTitles': ['', '', '', '', '#' ]},
		{'code': 'AltLeft', 'width': 12, 'shiftTitles': ['', '', '', '', 'alt' ]},
		{'code': 'Space', 'width': 50, 'shiftTitles': [' ', ' ', ' ', ' ', ' ' ]},
		{'code': 'AltRight', 'width': 12, 'shiftTitles': ['', '', '', '', 'alt' ]},
		{'code': 'ControlRight', 'width': 10, 'shiftTitles': ['', '', '', '', 'ctrl' ]},
		{'code': 'ArrowLeft', 'width': 10, 'shiftTitles': ['⯇', '⯇', '⯇', '⯇', '⯇' ]},
		{'code': 'ArrowDown', 'width': 10, 'shiftTitles': ['⯆', '⯆', '⯆', '⯆', '⯆' ]},
		{'code': 'ArrowRight', 'width': 10, 'shiftTitles': ['⯈', '⯈', '⯈', '⯈', '⯈' ]},
	]
]